
from pathlib import Path
from datetime import datetime

# Folders to scan recursively
# TARGET_FOLDERS = ['app','models']
TARGET_FOLDERS = ['app','01_cli_research_agent','projects','docs']


# File extensions to include
# TARGET_EXTENSIONS = ['.py', '.json', '.sql', '.md']
TARGET_EXTENSIONS = ['.py']

CODE_OUTPUT_FILE = "1_code.txt"
STRUCTURE_OUTPUT_FILE = "2_project_structure.txt"


EXCLUDE_DIRS = {
    "__pycache__",
    ".git",
    ".venv",
    "venv",
    "env",
    "Responsive",
    "Responsiwve",
    ".idea",
    "archive",
    "output",
    ".vscode",
    ".pytest_cache",
    "rag_Agent",
    "venv1",
    "code_Save.py",
    'SQL1',
    'tests',
    'Agent1',
}

def safe_read_text(file_path: Path) -> str:
    """Reads file content with fallback encoding."""
    try:
        return file_path.read_text(encoding="utf-8")
    except Exception:
        try:
            return file_path.read_text(encoding="latin-1")
        except Exception as e:
            return f"⚠️ ERROR reading file '{file_path}': {e}\n"


def generate_tree(dir_path: Path, prefix: str = "") -> list:
    """Recursively builds a visual folder structure."""
    tree_lines = []

    try:
        items = sorted(
            [p for p in dir_path.iterdir() if p.name not in EXCLUDE_DIRS],
            key=lambda p: (p.is_file(), p.name.lower())
        )
    except PermissionError:
        return [f"{prefix}└── [PERMISSION DENIED]"]

    for i, item in enumerate(items):
        is_last = i == (len(items) - 1)
        connector = "└── " if is_last else "├── "
        tree_lines.append(f"{prefix}{connector}{item.name}{'/' if item.is_dir() else ''}")
        if item.is_dir():
            extension = "    " if is_last else "│   "
            tree_lines.extend(generate_tree(item, prefix + extension))

    return tree_lines


def write_file_section(out, file_path: Path, project_root: Path):
    """Writes a single file's content with prominent identification."""
    rel_path = file_path.relative_to(project_root)

    out.write("\n")
    out.write("=" * 110 + "\n")
    out.write(f"📄 FILE: {rel_path}\n")
    out.write("=" * 110 + "\n\n")
    out.write(safe_read_text(file_path))
    out.write("\n")


def collect_files(folder_path: Path, current_script: Path) -> list:
    """Collect non-empty files matching TARGET_EXTENSIONS from a folder."""
    files = []
    for ext in TARGET_EXTENSIONS:
        for f in sorted(folder_path.rglob(f"*{ext}")):
            if any(part in EXCLUDE_DIRS for part in f.parts):
                continue
            if f.resolve() == current_script:
                continue
            if f.stat().st_size == 0:          # skip empty files
                continue
            files.append(f)
    return sorted(set(files))


def build_structure_file(project_root: Path):
    """Generates project_structure.txt — folder tree only."""
    output_path = project_root / STRUCTURE_OUTPUT_FILE

    with open(output_path, "w", encoding="utf-8") as out:
        out.write("=" * 110 + "\n")
        out.write(f"PROJECT STRUCTURE: {project_root.name}\n")
        out.write(f"GENERATED: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        out.write("=" * 110 + "\n\n")
        out.write(f"{project_root.name}/\n")
        out.write("\n".join(generate_tree(project_root)))
        out.write("\n")

    print(f"Structure file created at: {output_path.resolve()}")


def build_code_file(project_root: Path):
    """Generates master_code_file.txt — code content only."""
    output_path = project_root / CODE_OUTPUT_FILE
    current_script = Path(__file__).resolve()

    # 1. Collect root-level target files (excluding this script)
    root_files = sorted([
        f for f in project_root.iterdir()
        if f.is_file()
        and f.suffix in TARGET_EXTENSIONS
        and f.resolve() != current_script
        and f.stat().st_size > 0
    ])

    # 2. Collect files from target folders
    folder_contents = {}
    for folder_name in TARGET_FOLDERS:
        folder_path = project_root / folder_name
        if folder_path.exists() and folder_path.is_dir():
            files = collect_files(folder_path, current_script)
            if files:
                folder_contents[folder_name] = files

    with open(output_path, "w", encoding="utf-8") as out:
        # HEADER
        out.write("=" * 110 + "\n")
        out.write(f"PROJECT CODE FILE: {project_root.name}\n")
        out.write(f"GENERATED BY: {Path(__file__).name}\n")
        out.write(f"GENERATED:    {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        out.write(f"PROJECT ROOT: {project_root}\n")
        out.write("=" * 110 + "\n\n")

        # ROOT FILES
        out.write(f"### 1. ROOT LEVEL FILES ({len(root_files)} files) ###\n")
        if root_files:
            for file_path in root_files:
                write_file_section(out, file_path, project_root)
        else:
            out.write("\n(No root-level files found)\n")
        out.write("\n" + "=" * 110 + "\n\n")

        # TARGET FOLDERS
        section_num = 2
        for folder_name in TARGET_FOLDERS:
            if folder_name in folder_contents:
                count = len(folder_contents[folder_name])
                out.write(f"### {section_num}. {folder_name.upper()} FOLDER CONTENTS ({count} files) ###\n")
                for file_path in folder_contents[folder_name]:
                    write_file_section(out, file_path, project_root)
                section_num += 1
                out.write("\n" + "=" * 110 + "\n\n")

        # SUMMARY
        total_files = len(root_files) + sum(len(files) for files in folder_contents.values())
        out.write("### SUMMARY ###\n")
        out.write(f"Generated:             {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}\n")
        # out.write(f"Generated:             {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        out.write(f"Root files             : {len(root_files)}\n")
        for folder in TARGET_FOLDERS:
            count = len(folder_contents.get(folder, []))
            out.write(f"{folder}/ files         : {count}\n")
        out.write(f"TOTAL FILES            : {total_files}\n")

    print(f"Code file created at: {output_path.resolve()}")
    print(f"Total files extracted: {total_files}")


if __name__ == "__main__":
    project_root = Path(__file__).resolve().parent
    build_structure_file(project_root)
    build_code_file(project_root)
    print(f"Generated: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}")
    # print(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")